### ISSUE TITLE
这个项目目前只支持Mysql是吗？可否解释一下配置文件呢

### ISSUE THREAD

**Issue by xluos** [TEsTsLA/apijson#1]
这个项目目前只支持Mysql是吗？
可否解释一下配置文件呢？对于配置文件的后四个选项不太明白是做什么的

**Comment by TEsTsLA** [comment]
我觉得你还是看下 http://typeorm.io文档比较好，中文【http://typeorm.cn/#/】

**Comment by xluos** [comment]
> 觉得我还是你看下[http://typeorm.io文档比较好，中文【http://typeorm.cn/#/】](http://typeorm.io%E6%96%87%E6%A1%A3%E6%AF%94%E8%BE%83%E5%A5%BD%EF%BC%8C%E4%B8%AD%E6%96%87%E3%80%90http://typeorm.cn/#/%E3%80%91)

谢谢，不好意思以前没用过这个库不知道这个是typeorm的配置文件
